Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -83,18 +83,25 @@ jobs:
       
       - name: Test Application Connectivity
         run: |
+            echo "Waiting for the application to start..."
+            sleep 30
+  
             echo "Testing connectivity to the application using localhost..."
             curl -s -o /dev/null -w "Localhost HTTP Status: %{http_code}\n" http://localhost:8080/demo || echo "Failed to connect to localhost"
   
             echo "Testing connectivity to the application using service name..."
-            curl -s -o /dev/null -w "Service Name HTTP Status: %{http_code}\n" http://app:8080/demo || echo "Failed to connect to service name"
+            docker run --rm --network app-network curlimages/curl:latest curl -s -o /dev/null -w "Service Name HTTP Status: %{http_code}\n" http://app:8080/demo || echo "Failed to connect to service name"
 
-      - name: Deploy to Test
+      - name: Test Application Connectivity
         run: |
-            ./gradlew deployToTestWindowsLocal
-            PIPENV_IGNORE_VIRTUALENVS=1 pipenv install
-            ./gradlew waitForHeartBeat
-            curl http://zap:8080/JSON/core/action/newSession -s --proxy zap:8080
+          echo "Waiting for the application to start..."
+          sleep 30
+
+          echo "Testing connectivity to the application using localhost..."
+          curl -s -o /dev/null -w "Localhost HTTP Status: %{http_code}\n" http://localhost:8080/demo || echo "Failed to connect to localhost"
+
+          echo "Testing connectivity to the application using service name..."
+          docker run --rm --network app-network curlimages/curl:latest curl -s -o /dev/null -w "Service Name HTTP Status: %{http_code}\n" http://app:8080/demo || echo "Failed to connect to service name"
 
       - name: Security Dependency Analysis
         run: ./gradlew dependencyCheckAnalyze
